-- +goose up
CREATE TABLE IF NOT EXISTS "users" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "temp_data" (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "users"(id),
  data JSONB NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose down
DROP TABLE IF EXISTS "temp_data";
DROP TABLE IF EXISTS "users";
